version: 1.0.{build}
image: Visual Studio 2022

build_script:
  - echo Готово для подключения по RDP!
  - appveyor AddMessage "Подключайся по RDP"
  - ps: Start-Sleep -Seconds 3600

on_finish:
  - echo Билд завершён
